# Generated by Django 5.2.11 on 2026-02-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="domain",
            field=models.CharField(default="General", max_length=100),
        ),
    ]
